### ISSUE TITLE
Can't compile WebKit LowLevelInterpreter.cpp for MIPS with -mxgot

### ISSUE THREAD

**Issue by arichardson** [CTSRD-CHERI/llvm#225]
I used a combination of bugpoint and creduce on the generated IR to get the following reduced test case:

```
; RUN: llc -target-abi n64 -relocation-model=pic -mxgot -o /dev/null %s
; ModuleID = 'new-webkit2.creduce.test.creduce.ll-reduced-simplified.bc'
source_filename = "new-webkit2.creduce.test.creduce.ll-output-33efd2f.bc"
target triple = "mips64-unknownfreebsd12"

%"class.JSC::VM.622.1251.1880.620.1244.1868.0.2.4" = type {}
%"struct.JSC::ProtoCallFrame.623.1252.1881.621.1245.1869.1.3.5" = type {}

define { i64 } @a(i32, i8, %"class.JSC::VM.622.1251.1880.620.1244.1868.0.2.4", %"struct.JSC::ProtoCallFrame.623.1252.1881.621.1245.1869.1.3.5", i1) {
  br i1 undef, label %6, label %8

; <label>:6:                                      ; preds = %5
  %7 = call i8* @b(i8* blockaddress(@a, %8))
  ret { i64 } undef

; <label>:8:                                      ; preds = %8, %5
  br label %8
}

declare i8* @b(i8*)

```
which results in the following error:
```
LLVM ERROR: Cannot select: 0x42054d8: i64 = MipsISD::GotHi TargetBlockAddress:i64<@a, %8> 0 [TF=20]
  0x4205470: i64 = TargetBlockAddress<@a, %8> 0 [TF=20]
In function: a
```

It compiles fine without mxgot.

**Comment by davidchisnall** [comment]
This looks as if it's a bug in the upstream code (pure MIPS)?

**Comment by davidchisnall** [comment]
It appears that LLVM upstream always generates a `%got_page` reloc (GOT entry for the page containing the function) on a load and then a `%got_disp` reloc on an add to find the offset of the block within the page.  `%got_page` supports only 16-bit-offset GOT entries.  

The simplest thing to do is fall back to emitting the `%got_page` entry (as upstream does) and hope that the linker can sort the GOT entries so that these are all in range.  Fixing it properly will require us to emit a new kind of node and then expand it later once we can put the MCSymbol in the right place.
