### ISSUE TITLE
Miscompile while using the strchr builtin

### ISSUE THREAD

**Issue by zxombie** [CTSRD-CHERI/llvm#253]
LLVM seems to miscompile the following

    #include <string.h>
    char *test(char *s) {
        while (strchr(",;", *s))
            s++;
        return s;
    }

It is taking a flag to indicate it has matched the character then turn it into a capability and compare with the null capability.

**Comment by davidchisnall** [comment]
The transform is almost correct.  It replace the `strchr` call with a bitmask containing `((1 << ',') | (1 << ';'))` that is then anded with `*s` so that get a value that is 0 if the character is not `','` or `';'`, or something else otherwise.  This all works fine right up until the point where it is converted to a capability with an `inttoptr` instruction.  It's slightly nontrivial to fix, because place where the `inttoptr` is constructed isn't expected to modify the `icmp`.

**Comment by davidchisnall** [comment]
Actually, it looks as if this can be fixed by making the transform return a select of null or the source string, and then relying on instcombine to notice that an icmp of null or not-null with null can be folded.
